import type { Config, Rules } from '../types'
import { pluginJson, pluginYml } from '../plugins'

export const sortPackageJson = (): Config[] => [
  {
    files: ['**/package.json'],
    language: 'jsonc/x',
    name: 'tanny/sort/package-json',
    plugins: {
      jsonc: pluginJson,
    },
    rules: {
      'jsonc/sort-array-values': [
        'error',
        {
          order: { type: 'asc' },
          pathPattern: '^files$',
        },
      ],
      'jsonc/sort-keys': [
        'error',
        {
          order: [
            'publisher',
            'name',
            'displayName',
            'type',
            'version',
            'private',
            'packageManager',
            'description',
            'author',
            'contributors',
            'license',
            'funding',
            'homepage',
            'repository',
            'bugs',
            'keywords',
            'categories',
            'sideEffects',
            'imports',
            'exports',
            'main',
            'module',
            'unpkg',
            'jsdelivr',
            'types',
            'typesVersions',
            'bin',
            'icon',
            'files',
            'engines',
            'activationEvents',
            'contributes',
            'scripts',
            'peerDependencies',
            'peerDependenciesMeta',
            'dependencies',
            'optionalDependencies',
            'devDependencies',
            'pnpm',
            'overrides',
            'resolutions',
            'husky',
            'simple-git-hooks',
            'lint-staged',
            'eslintConfig',
          ],
          pathPattern: '^$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '^workspaces\\.catalog$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '^workspaces\\.catalogs\\.[^.]+$',
        },
        {
          order: ['types', 'import', 'require', 'default'],
          pathPattern: '^exports.*$',
        },
        {
          order: [
            'pre-commit',
            'prepare-commit-msg',
            'commit-msg',
            'post-commit',
            'pre-rebase',
            'post-rewrite',
            'post-checkout',
            'post-merge',
            'pre-push',
            'pre-auto-gc',
          ],
          pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
        },
      ],
    } satisfies Rules,
  },
]

export const sortTsconfig = (): Config[] => [
  {
    files: ['**/[jt]sconfig.json', '**/[jt]sconfig.*.json'],
    language: 'jsonc/x',
    name: 'tanny/sort/tsconfig-json',
    plugins: {
      jsonc: pluginJson,
    },
    rules: {
      'jsonc/sort-keys': [
        'error',
        {
          order: [
            'extends',
            'compilerOptions',
            'references',
            'files',
            'include',
            'exclude',
          ],
          pathPattern: '^$',
        },
        {
          order: [
            'incremental',
            'composite',
            'tsBuildInfoFile',
            'disableSourceOfProjectReferenceRedirect',
            'disableSolutionSearching',
            'disableReferencedProjectLoad',
            'target',
            'jsx',
            'jsxFactory',
            'jsxFragmentFactory',
            'jsxImportSource',
            'lib',
            'moduleDetection',
            'noLib',
            'reactNamespace',
            'useDefineForClassFields',
            'emitDecoratorMetadata',
            'experimentalDecorators',
            'libReplacement',
            'baseUrl',
            'rootDir',
            'rootDirs',
            'customConditions',
            'module',
            'moduleResolution',
            'moduleSuffixes',
            'noResolve',
            'paths',
            'resolveJsonModule',
            'resolvePackageJsonExports',
            'resolvePackageJsonImports',
            'typeRoots',
            'types',
            'allowArbitraryExtensions',
            'allowImportingTsExtensions',
            'allowUmdGlobalAccess',
            'allowJs',
            'checkJs',
            'maxNodeModuleJsDepth',
            'strict',
            'strictBindCallApply',
            'strictFunctionTypes',
            'strictNullChecks',
            'strictPropertyInitialization',
            'allowUnreachableCode',
            'allowUnusedLabels',
            'alwaysStrict',
            'exactOptionalPropertyTypes',
            'noFallthroughCasesInSwitch',
            'noImplicitAny',
            'noImplicitOverride',
            'noImplicitReturns',
            'noImplicitThis',
            'noPropertyAccessFromIndexSignature',
            'noUncheckedIndexedAccess',
            'noUnusedLocals',
            'noUnusedParameters',
            'useUnknownInCatchVariables',
            'declaration',
            'declarationDir',
            'declarationMap',
            'downlevelIteration',
            'emitBOM',
            'emitDeclarationOnly',
            'importHelpers',
            'importsNotUsedAsValues',
            'inlineSourceMap',
            'inlineSources',
            'mapRoot',
            'newLine',
            'noEmit',
            'noEmitHelpers',
            'noEmitOnError',
            'outDir',
            'outFile',
            'preserveConstEnums',
            'preserveValueImports',
            'removeComments',
            'sourceMap',
            'sourceRoot',
            'stripInternal',
            'allowSyntheticDefaultImports',
            'esModuleInterop',
            'forceConsistentCasingInFileNames',
            'isolatedDeclarations',
            'isolatedModules',
            'preserveSymlinks',
            'verbatimModuleSyntax',
            'erasableSyntaxOnly',
            'skipDefaultLibCheck',
            'skipLibCheck',
          ],
          pathPattern: '^compilerOptions$',
        },
      ],
    } satisfies Rules,
  },
]

export const sortPnpmWorkspace = (): Config[] => [
  {
    files: ['pnpm-workspace.yaml'],
    language: 'yml/yaml',
    name: 'tanny/sort/pnpm-workspace',
    plugins: {
      yml: pluginYml,
    },
    rules: {
      'yml/sort-keys': [
        'error',
        {
          order: [
            'cacheDir',
            'catalogMode',
            'cleanupUnusedCatalogs',
            'dedupeDirectDeps',
            'deployAllFiles',
            'enablePrePostScripts',
            'engineStrict',
            'extendNodePath',
            'hoist',
            'hoistPattern',
            'hoistWorkspacePackages',
            'ignoreCompatibilityDb',
            'ignoreDepScripts',
            'ignoreScripts',
            'ignoreWorkspaceRootCheck',
            'managePackageManagerVersions',
            'minimumReleaseAge',
            'minimumReleaseAgeExclude',
            'modulesDir',
            'nodeLinker',
            'nodeVersion',
            'optimisticRepeatInstall',
            'packageManagerStrict',
            'packageManagerStrictVersion',
            'preferSymlinkedExecutables',
            'preferWorkspacePackages',
            'publicHoistPattern',
            'registrySupportsTimeField',
            'requiredScripts',
            'resolutionMode',
            'savePrefix',
            'scriptShell',
            'shamefullyHoist',
            'shellEmulator',
            'stateDir',
            'supportedArchitectures',
            'symlink',
            'tag',
            'trustPolicy',
            'trustPolicyExclude',
            'updateNotifier',
            'packages',
            'overrides',
            'patchedDependencies',
            'catalog',
            'catalogs',
            'allowedDeprecatedVersions',
            'allowNonAppliedPatches',
            'configDependencies',
            'ignoredBuiltDependencies',
            'ignoredOptionalDependencies',
            'neverBuiltDependencies',
            'onlyBuiltDependencies',
            'onlyBuiltDependenciesFile',
            'packageExtensions',
            'peerDependencyRules',
          ],
          pathPattern: '^$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '.*',
        },
      ],
    } satisfies Rules,
  },
]

export const sort = (): Config[] => [
  ...sortPackageJson(),
  ...sortTsconfig(),
  ...sortPnpmWorkspace(),
]
